### ISSUE TITLE
js. and .ts files must import React explicitly: (Uncaught ReferenceError: React is not defined)

### ISSUE THREAD

**Issue by franciscop** [tajo/ladle#54] opened 2022-03-16 02:12 UTC
I've tried the example code and I'm getting an empty story:

<img width="1440" alt="Screen Shot 2022-03-16 at 11 00 36" src="https://user-images.githubusercontent.com/2801252/158501967-f0972bd0-b0ff-4fc2-994d-ab399858714e.png">

Upon inspecting my console, there's this error:

```
Uncaught ReferenceError: React is not defined
...
```

I'm running it with `npx ladle serve`, and both that and `npx ladle build` + a local webserver will render the frame properly, receive the correct data when clicking on the component (as seen in the example), but not render the component on the left. So I changed this code:

```js
export default {
  title: "Level / Sub level",
};
export const Button = () => <button>My Button</button>;
```

Into this one, and *now it works*, note the first line change:

```js
import React from "react";

export default {
  title: "Level / Sub level",
};
export const Button = () => <button>My Button</button>;
```

My react version is 17.0.2 (same as `react-dom`) since 18.x is not yet official. *Should we add the `import React from "react";` to the docs?* Or maybe I'm missing some config that would make it not needed? The only different thing I'm doing is running it with `npx ladle serve` instead of `yarn ladle serve` otherwise.

**Comment by tajo** [comment] 2022-03-16 03:55
I cannot reproduce that locally or with [StackBlitz](https://stackblitz.com/edit/ladle-weqjfh?file=src%2Fbasic.stories.tsx).

Using `npx` vs `yarn` should not matter. Maybe you can provide a repo? From your screenshots it seems that JSX runtime was not injected correctly and React is still referenced.

**Comment by franciscop** [comment] 2022-03-16 05:05
I'm setting up a full repro, but quick question just in case, I'm using it as `hello.stories.js`, does it matter? Should I be using `.jsx` instead?

**Comment by franciscop** [comment] 2022-03-16 05:10
Full repro can be done with these lines of code; I also set up [a repo in Github](https://github.com/franciscop/repro-ladle):

```
mkdir repro-ladle
cd repro-ladle
npx create-react-app .
npm i --save-dev @ladle/react
echo "export const World = () => <p>Hey</p>;" > src/hello.stories.js
npx ladle serve
```

**Comment by tajo** [comment] 2022-03-16 05:41
Thanks for the repro.

> Should I be using `.jsx` instead?

Yes. I know there are a lot of heated arguments about this but the fact is that modern tools like `esbuild` and `vite` are primarly built around the assumption that JSX is only present in `.jsx` or `.tsx` files. CRA is really weird in this respect.

What's probably happening here is Vite (or its plugin) thinking that module is plain JS and not injecting the JSX runtime into it.

 I can check if there's is some solution for this but my recommendation would be using keeping `.js` only for JS valid syntax. Also the workaround of importing React is not that bad anyway.

**Comment by franciscop** [comment] 2022-03-16 05:57
React team [officially recommends](https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904) using `.js` for JSX files, so I think we could/should at least add a tip on the documentation if this tool is not going to work with the React official way? Is there a way to [configure ladle](https://www.ladle.dev/docs/config) to use `js` for JSX?

**Comment by franciscop** [comment] 2022-03-16 05:59
> Also the workaround of importing React is not that bad anyway.

That's what I found odd, it's not complaining about JSX `<p>` syntax, it's complaining about the lack of React, so I thought might be a different bug.

**Comment by tajo** [comment] 2022-03-16 19:30
`.js` and `.ts` files must awlays import React

```js
import * as React from 'react';
```

Vite is not injecting JSX runtime in that case, only for `.jsx` and `.tsx` files. It seems it's something they are not going to change since it also has some performance reasons (babel transforming all .js files would be costly) 

https://github.com/vitejs/vite/blob/main/packages/plugin-react/src/index.ts#L168

Closing this as `won't fix`.

**Closed by tajo** 2022-03-16 19:30 UTC
Labels: wontfix

**Comment by franciscop** [comment] 2022-03-16 22:58
I understand Vite is the exception here about requiring `.jsx` for JSX files and in my experience the vast majority of React projects use `.js` for JSX files; I'd at least suggest to check the top N React projects and evaluate whether they use `.js` or `.jsx` before dismissing using JSX inside `.js` as a "really weird" case.

> Closing this as won't fix.

My suggestion and why I kept this open is that even if this is a "won't fix" code-wise (100% respect that), I'd suggest adding a note somewhere in the "Setup". Something along the lines:

> "When using JSX syntax for your stories you *must* make sure to use the extension `.jsx` or `.tsx` since Vite uses this for performance. If you want to write JSX inside a `*.stories.js` file, you'll need to add `import * as React from 'react';` manually to the top of those files."

**Comment by tajo** [comment] 2022-03-16 23:23
Added a note to the setup. Again, not going to fork Vite because of this.

**Comment by franciscop** [comment] 2022-03-17 00:25
> Again, not going to fork Vite because of this.

Never was my suggestion to fork Vite :)

> Added a note to the setup.

Awesome, that works, thanks!
