### ISSUE TITLE
Ladle stories are not picking up the meta args

### ISSUE THREAD

**Issue by imgio** [tajo/ladle#303] opened 2023-01-04 21:57 UTC
**Description**
Let's say we have the following Storybook story: 

```
import React from 'react'
import { ComponentMeta, ComponentStory } from '@storybook/react'
import { Typography } from '../../Typography'

const meta: ComponentMeta<typeof Typography> = {
  title: 'atoms/actions/TestLabel',
  component: Typography,
  args: {
    label: 'Label',
  },
}
export default meta

const Template: ComponentStory<typeof Typography> = args => {
  return `Label: ${args.label}`
}

export const Story1 = Template.bind({})
```
What Storybook displays for this story is: 
**Label: Label**

What Ladle displays for this story is:
**Label: undefined**

Looks like Ladle is having trouble reading the args from the meta. 
Is there a way to make this work? 

We have stories in our codebase where the meta has 'global' args and if there are 5 components defined in the same file, they all share the global meta args. 
Looking for a solution that does not involve defining the args individually for each component.

**Comment by tajo** [comment] 2023-01-09 11:52
Yes, I ran into this too - we should add support for per file args/argTypes.

**Comment by some-dudes-work-account** [comment] 2023-01-17 05:36
is this a duplicate of #290?

**Comment by tajo** [comment] 2023-01-17 11:43
closing as duplicated

**Closed by tajo** 2023-01-17 11:43 UTC
Labels: duplicate, enhancement
